---
project_name: multicode

before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/decode/main.go
    binary: decode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next-{{.Commit}}"
# nfpms:
#   - maintainer: Simon Jürgensmeyyer <simon.juergensmeyer@gmail.com>
#     homepage: https://github.com/sj14/multicode/
#     description: Decode bits, hex, base64 and protobuf recursively with a single command
#     license: MIT
#     formats:
#       - deb
#       - rpm
#       - apk # not tested
brews:
  - name: multicode
    skip_upload: auto
    tap:
      owner: sj14
      name: homebrew-tap
    description: "Decode bits, hex, base64 and protobuf recursively with a single command"
release:
  github:
    owner: sj14
    name: multicode
  disable: false
  draft: false
  prerelease: auto
changelog:
  filters:
    exclude:
      - typo
