// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protodec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ComplexMessage_Corpus int32

const (
	ComplexMessage_UNIVERSAL ComplexMessage_Corpus = 0
	ComplexMessage_WEB       ComplexMessage_Corpus = 1
	ComplexMessage_IMAGES    ComplexMessage_Corpus = 2
	ComplexMessage_LOCAL     ComplexMessage_Corpus = 3
	ComplexMessage_NEWS      ComplexMessage_Corpus = 4
	ComplexMessage_PRODUCTS  ComplexMessage_Corpus = 5
	ComplexMessage_VIDEO     ComplexMessage_Corpus = 6
)

var ComplexMessage_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var ComplexMessage_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x ComplexMessage_Corpus) String() string {
	return proto.EnumName(ComplexMessage_Corpus_name, int32(x))
}

func (ComplexMessage_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SimpleMessage struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleMessage) Reset()         { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()    {}
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *SimpleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMessage.Unmarshal(m, b)
}
func (m *SimpleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMessage.Marshal(b, m, deterministic)
}
func (m *SimpleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMessage.Merge(m, src)
}
func (m *SimpleMessage) XXX_Size() int {
	return xxx_messageInfo_SimpleMessage.Size(m)
}
func (m *SimpleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMessage proto.InternalMessageInfo

func (m *SimpleMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ComplexMessage struct {
	Query                string                `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32                 `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32                 `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Corpus               ComplexMessage_Corpus `protobuf:"varint,4,opt,name=corpus,proto3,enum=protodec.ComplexMessage_Corpus" json:"corpus,omitempty"`
	Results              []*Result             `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	Details              []*any.Any            `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty"`
	Sample               *SampleMessage        `protobuf:"bytes,7,opt,name=sample,proto3" json:"sample,omitempty"`
	Projects             map[string]*Result    `protobuf:"bytes,8,rep,name=projects,proto3" json:"projects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ComplexMessage) Reset()         { *m = ComplexMessage{} }
func (m *ComplexMessage) String() string { return proto.CompactTextString(m) }
func (*ComplexMessage) ProtoMessage()    {}
func (*ComplexMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ComplexMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexMessage.Unmarshal(m, b)
}
func (m *ComplexMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexMessage.Marshal(b, m, deterministic)
}
func (m *ComplexMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexMessage.Merge(m, src)
}
func (m *ComplexMessage) XXX_Size() int {
	return xxx_messageInfo_ComplexMessage.Size(m)
}
func (m *ComplexMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexMessage proto.InternalMessageInfo

func (m *ComplexMessage) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ComplexMessage) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *ComplexMessage) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *ComplexMessage) GetCorpus() ComplexMessage_Corpus {
	if m != nil {
		return m.Corpus
	}
	return ComplexMessage_UNIVERSAL
}

func (m *ComplexMessage) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ComplexMessage) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *ComplexMessage) GetSample() *SampleMessage {
	if m != nil {
		return m.Sample
	}
	return nil
}

func (m *ComplexMessage) GetProjects() map[string]*Result {
	if m != nil {
		return m.Projects
	}
	return nil
}

type SampleMessage struct {
	// Types that are valid to be assigned to TestOneof:
	//	*SampleMessage_Name
	//	*SampleMessage_SubMessage
	TestOneof            isSampleMessage_TestOneof `protobuf_oneof:"test_oneof"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SampleMessage) Reset()         { *m = SampleMessage{} }
func (m *SampleMessage) String() string { return proto.CompactTextString(m) }
func (*SampleMessage) ProtoMessage()    {}
func (*SampleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *SampleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleMessage.Unmarshal(m, b)
}
func (m *SampleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleMessage.Marshal(b, m, deterministic)
}
func (m *SampleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleMessage.Merge(m, src)
}
func (m *SampleMessage) XXX_Size() int {
	return xxx_messageInfo_SampleMessage.Size(m)
}
func (m *SampleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SampleMessage proto.InternalMessageInfo

type isSampleMessage_TestOneof interface {
	isSampleMessage_TestOneof()
}

type SampleMessage_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}

type SampleMessage_SubMessage struct {
	SubMessage *Outer `protobuf:"bytes,9,opt,name=sub_message,json=subMessage,proto3,oneof"`
}

func (*SampleMessage_Name) isSampleMessage_TestOneof() {}

func (*SampleMessage_SubMessage) isSampleMessage_TestOneof() {}

func (m *SampleMessage) GetTestOneof() isSampleMessage_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *SampleMessage) GetName() string {
	if x, ok := m.GetTestOneof().(*SampleMessage_Name); ok {
		return x.Name
	}
	return ""
}

func (m *SampleMessage) GetSubMessage() *Outer {
	if x, ok := m.GetTestOneof().(*SampleMessage_SubMessage); ok {
		return x.SubMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SampleMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SampleMessage_Name)(nil),
		(*SampleMessage_SubMessage)(nil),
	}
}

type Result struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets             []string `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

type Outer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer) Reset()         { *m = Outer{} }
func (m *Outer) String() string { return proto.CompactTextString(m) }
func (*Outer) ProtoMessage()    {}
func (*Outer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Outer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer.Unmarshal(m, b)
}
func (m *Outer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer.Marshal(b, m, deterministic)
}
func (m *Outer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer.Merge(m, src)
}
func (m *Outer) XXX_Size() int {
	return xxx_messageInfo_Outer.Size(m)
}
func (m *Outer) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer.DiscardUnknown(m)
}

var xxx_messageInfo_Outer proto.InternalMessageInfo

type Outer_MiddleAA struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer_MiddleAA) Reset()         { *m = Outer_MiddleAA{} }
func (m *Outer_MiddleAA) String() string { return proto.CompactTextString(m) }
func (*Outer_MiddleAA) ProtoMessage()    {}
func (*Outer_MiddleAA) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5, 0}
}

func (m *Outer_MiddleAA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer_MiddleAA.Unmarshal(m, b)
}
func (m *Outer_MiddleAA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer_MiddleAA.Marshal(b, m, deterministic)
}
func (m *Outer_MiddleAA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer_MiddleAA.Merge(m, src)
}
func (m *Outer_MiddleAA) XXX_Size() int {
	return xxx_messageInfo_Outer_MiddleAA.Size(m)
}
func (m *Outer_MiddleAA) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer_MiddleAA.DiscardUnknown(m)
}

var xxx_messageInfo_Outer_MiddleAA proto.InternalMessageInfo

type Outer_MiddleAA_Inner struct {
	Ival                 int64    `protobuf:"varint,1,opt,name=ival,proto3" json:"ival,omitempty"`
	Booly                bool     `protobuf:"varint,2,opt,name=booly,proto3" json:"booly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer_MiddleAA_Inner) Reset()         { *m = Outer_MiddleAA_Inner{} }
func (m *Outer_MiddleAA_Inner) String() string { return proto.CompactTextString(m) }
func (*Outer_MiddleAA_Inner) ProtoMessage()    {}
func (*Outer_MiddleAA_Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5, 0, 0}
}

func (m *Outer_MiddleAA_Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer_MiddleAA_Inner.Unmarshal(m, b)
}
func (m *Outer_MiddleAA_Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer_MiddleAA_Inner.Marshal(b, m, deterministic)
}
func (m *Outer_MiddleAA_Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer_MiddleAA_Inner.Merge(m, src)
}
func (m *Outer_MiddleAA_Inner) XXX_Size() int {
	return xxx_messageInfo_Outer_MiddleAA_Inner.Size(m)
}
func (m *Outer_MiddleAA_Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer_MiddleAA_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_Outer_MiddleAA_Inner proto.InternalMessageInfo

func (m *Outer_MiddleAA_Inner) GetIval() int64 {
	if m != nil {
		return m.Ival
	}
	return 0
}

func (m *Outer_MiddleAA_Inner) GetBooly() bool {
	if m != nil {
		return m.Booly
	}
	return false
}

type Outer_MiddleBB struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer_MiddleBB) Reset()         { *m = Outer_MiddleBB{} }
func (m *Outer_MiddleBB) String() string { return proto.CompactTextString(m) }
func (*Outer_MiddleBB) ProtoMessage()    {}
func (*Outer_MiddleBB) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5, 1}
}

func (m *Outer_MiddleBB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer_MiddleBB.Unmarshal(m, b)
}
func (m *Outer_MiddleBB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer_MiddleBB.Marshal(b, m, deterministic)
}
func (m *Outer_MiddleBB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer_MiddleBB.Merge(m, src)
}
func (m *Outer_MiddleBB) XXX_Size() int {
	return xxx_messageInfo_Outer_MiddleBB.Size(m)
}
func (m *Outer_MiddleBB) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer_MiddleBB.DiscardUnknown(m)
}

var xxx_messageInfo_Outer_MiddleBB proto.InternalMessageInfo

type Outer_MiddleBB_Inner struct {
	Ival                 int32    `protobuf:"varint,1,opt,name=ival,proto3" json:"ival,omitempty"`
	Booly                bool     `protobuf:"varint,2,opt,name=booly,proto3" json:"booly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer_MiddleBB_Inner) Reset()         { *m = Outer_MiddleBB_Inner{} }
func (m *Outer_MiddleBB_Inner) String() string { return proto.CompactTextString(m) }
func (*Outer_MiddleBB_Inner) ProtoMessage()    {}
func (*Outer_MiddleBB_Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5, 1, 0}
}

func (m *Outer_MiddleBB_Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer_MiddleBB_Inner.Unmarshal(m, b)
}
func (m *Outer_MiddleBB_Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer_MiddleBB_Inner.Marshal(b, m, deterministic)
}
func (m *Outer_MiddleBB_Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer_MiddleBB_Inner.Merge(m, src)
}
func (m *Outer_MiddleBB_Inner) XXX_Size() int {
	return xxx_messageInfo_Outer_MiddleBB_Inner.Size(m)
}
func (m *Outer_MiddleBB_Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer_MiddleBB_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_Outer_MiddleBB_Inner proto.InternalMessageInfo

func (m *Outer_MiddleBB_Inner) GetIval() int32 {
	if m != nil {
		return m.Ival
	}
	return 0
}

func (m *Outer_MiddleBB_Inner) GetBooly() bool {
	if m != nil {
		return m.Booly
	}
	return false
}

func init() {
	proto.RegisterEnum("protodec.ComplexMessage_Corpus", ComplexMessage_Corpus_name, ComplexMessage_Corpus_value)
	proto.RegisterType((*Empty)(nil), "protodec.Empty")
	proto.RegisterType((*SimpleMessage)(nil), "protodec.SimpleMessage")
	proto.RegisterType((*ComplexMessage)(nil), "protodec.ComplexMessage")
	proto.RegisterMapType((map[string]*Result)(nil), "protodec.ComplexMessage.ProjectsEntry")
	proto.RegisterType((*SampleMessage)(nil), "protodec.SampleMessage")
	proto.RegisterType((*Result)(nil), "protodec.Result")
	proto.RegisterType((*Outer)(nil), "protodec.Outer")
	proto.RegisterType((*Outer_MiddleAA)(nil), "protodec.Outer.MiddleAA")
	proto.RegisterType((*Outer_MiddleAA_Inner)(nil), "protodec.Outer.MiddleAA.Inner")
	proto.RegisterType((*Outer_MiddleBB)(nil), "protodec.Outer.MiddleBB")
	proto.RegisterType((*Outer_MiddleBB_Inner)(nil), "protodec.Outer.MiddleBB.Inner")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xdd, 0x6e, 0x9b, 0x30,
	0x14, 0xc7, 0x4b, 0x09, 0x04, 0x4e, 0x9a, 0x16, 0x59, 0x95, 0xc6, 0x72, 0xd3, 0x88, 0x49, 0x55,
	0xb4, 0x0b, 0xaa, 0x65, 0x17, 0x9b, 0x26, 0xed, 0x22, 0x49, 0xd1, 0x1a, 0x29, 0x69, 0x22, 0xb3,
	0xb6, 0xd2, 0x6e, 0x22, 0x68, 0xdc, 0x88, 0x8d, 0x00, 0xb3, 0x4d, 0x55, 0x1e, 0x60, 0x6f, 0xb2,
	0x07, 0x9d, 0x6c, 0x43, 0xb3, 0x48, 0xdd, 0xae, 0xf0, 0x39, 0xe7, 0x77, 0xbe, 0xfe, 0x36, 0xd0,
	0xdd, 0x12, 0xc6, 0xa2, 0x0d, 0xf1, 0x0b, 0x9a, 0xf3, 0x1c, 0x59, 0xf2, 0xb3, 0x26, 0xf7, 0xbd,
	0xd7, 0x9b, 0x3c, 0xdf, 0xa4, 0xe4, 0x42, 0x3a, 0xe2, 0xf2, 0xe1, 0x22, 0xca, 0x2a, 0x05, 0x79,
	0x6d, 0x30, 0x82, 0x6d, 0xc1, 0x2b, 0xef, 0x0d, 0x74, 0xc3, 0x64, 0x5b, 0xa4, 0x64, 0xae, 0x8a,
	0x20, 0x04, 0x2d, 0x4e, 0x9e, 0xb8, 0xab, 0xf5, 0xb5, 0x81, 0x8d, 0xe5, 0xd9, 0xfb, 0xdd, 0x82,
	0xe3, 0x49, 0x2e, 0xa8, 0xa7, 0x06, 0x3b, 0x05, 0xe3, 0x67, 0x49, 0x68, 0x55, 0x73, 0xca, 0x40,
	0x67, 0xd0, 0x29, 0xa2, 0x0d, 0x59, 0x65, 0xe5, 0x36, 0x26, 0xd4, 0x3d, 0xec, 0x6b, 0x03, 0x03,
	0x83, 0x70, 0x5d, 0x4b, 0x0f, 0x3a, 0x87, 0x13, 0x4a, 0x58, 0x99, 0xf2, 0x55, 0x41, 0xe8, 0x4a,
	0x04, 0x5c, 0x5d, 0x42, 0x5d, 0xe5, 0x5e, 0x12, 0xba, 0x14, 0xe5, 0x3f, 0x80, 0x79, 0x9f, 0xd3,
	0xa2, 0x64, 0x6e, 0xab, 0xaf, 0x0d, 0x8e, 0x87, 0x67, 0x7e, 0xb3, 0x95, 0xbf, 0x3f, 0x88, 0x3f,
	0x91, 0x18, 0xae, 0x71, 0xf4, 0x16, 0xda, 0xaa, 0x12, 0x73, 0x8d, 0xbe, 0x3e, 0xe8, 0x0c, 0x9d,
	0x5d, 0x26, 0x96, 0x01, 0xdc, 0x00, 0xc8, 0x87, 0xf6, 0x9a, 0xf0, 0x28, 0x49, 0x99, 0x6b, 0x4a,
	0xf6, 0xd4, 0x57, 0x8a, 0xf9, 0x8d, 0x62, 0xfe, 0x28, 0xab, 0x70, 0x03, 0xa1, 0x0b, 0x30, 0x59,
	0x24, 0x9a, 0xbb, 0xed, 0xbe, 0x36, 0xe8, 0x0c, 0x5f, 0xed, 0x4a, 0x87, 0xd1, 0x5f, 0x1a, 0xe2,
	0x1a, 0x43, 0x63, 0x10, 0x97, 0xf1, 0x9d, 0xdc, 0x73, 0xe6, 0x5a, 0xb2, 0xc3, 0xf9, 0x3f, 0xf7,
	0x58, 0xd6, 0x60, 0x90, 0x71, 0x5a, 0xe1, 0xe7, 0xbc, 0xde, 0x1c, 0xba, 0x7b, 0x21, 0xe4, 0x80,
	0xfe, 0x83, 0x34, 0xba, 0x8b, 0x23, 0x3a, 0x07, 0xe3, 0x31, 0x4a, 0x4b, 0x22, 0xf5, 0x7e, 0x69,
	0x63, 0x15, 0xfe, 0x74, 0xf8, 0x51, 0xf3, 0xbe, 0x81, 0xa9, 0x14, 0x43, 0x5d, 0xb0, 0x6f, 0xae,
	0xa7, 0xb7, 0x01, 0x0e, 0x47, 0x33, 0xe7, 0x00, 0xb5, 0x41, 0xbf, 0x0b, 0xc6, 0x8e, 0x86, 0x00,
	0xcc, 0xe9, 0x7c, 0xf4, 0x25, 0x08, 0x9d, 0x43, 0x64, 0x83, 0x31, 0x5b, 0x4c, 0x46, 0x33, 0x47,
	0x47, 0x16, 0xb4, 0xae, 0x83, 0xbb, 0xd0, 0x69, 0xa1, 0x23, 0xb0, 0x96, 0x78, 0x71, 0x79, 0x33,
	0xf9, 0x1a, 0x3a, 0x86, 0x40, 0x6e, 0xa7, 0x97, 0xc1, 0xc2, 0x31, 0xbd, 0x0d, 0x74, 0xf7, 0x74,
	0x40, 0xa7, 0xd0, 0xca, 0xa2, 0x2d, 0x91, 0x77, 0x68, 0x5f, 0x1d, 0x60, 0x69, 0xa1, 0x21, 0x74,
	0x58, 0x19, 0xaf, 0xea, 0x57, 0xeb, 0xda, 0x72, 0xe8, 0x93, 0xdd, 0xd0, 0x8b, 0x92, 0x13, 0x7a,
	0x75, 0x80, 0x81, 0x95, 0x71, 0x5d, 0x69, 0x7c, 0x04, 0xc0, 0x09, 0xe3, 0xab, 0x3c, 0x23, 0xf9,
	0x83, 0x37, 0x03, 0x53, 0x6d, 0x26, 0xc4, 0x28, 0x69, 0xda, 0x88, 0x51, 0xd2, 0x54, 0x3c, 0x4c,
	0x9e, 0xf0, 0x54, 0x89, 0x61, 0x63, 0x65, 0xa0, 0x1e, 0x58, 0x2c, 0x4b, 0x8a, 0x82, 0x70, 0xe6,
	0xea, 0x7d, 0x7d, 0x60, 0xe3, 0x67, 0xdb, 0xfb, 0xa5, 0x81, 0x21, 0x7b, 0xf6, 0x3e, 0x83, 0x35,
	0x4f, 0xd6, 0xeb, 0x94, 0x8c, 0x46, 0xbd, 0x77, 0x60, 0x4c, 0xb3, 0x8c, 0x50, 0xf1, 0x43, 0x24,
	0x8f, 0x91, 0xea, 0xa1, 0x63, 0x79, 0x16, 0x4d, 0xe2, 0x3c, 0x4f, 0x2b, 0xd9, 0xc4, 0xc2, 0xca,
	0xd8, 0xa5, 0x8f, 0xc7, 0x2f, 0xa7, 0x1b, 0xff, 0x4b, 0x8f, 0x4d, 0xa9, 0xc0, 0xfb, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x0a, 0x1c, 0x90, 0x81, 0xd0, 0x03, 0x00, 0x00,
}
